version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: montink_test_app
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
      - socket
    networks:
      - montink_net

  db:
    image: mysql:5.7
    container_name: montink_test_db
    restart: always
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - montink_net

  socket:
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    container_name: montink_test_socket
    ports:
      - "${SOCKET_PORT:-3000}:${SOCKET_PORT:-3000}"
    environment:
      - SOCKET_PORT=${SOCKET_PORT:-3000}
    networks:
      - montink_net

volumes:
  db_data:

networks:
  montink_net:
    driver: bridge
